function template(locals) {
var jade_debug = [{ lineno: 1, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (undefined) {
jade_debug.unshift({ lineno: 0, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
jade_debug.unshift({ lineno: 1, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<link rel=\"stylesheet\" src=\"bower_components/mediaelement/build/mediaelementplayer.css\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<h1>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 2, filename: jade_debug[0].filename });
buf.push("Spot test");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift({ lineno: 4, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<button onclick=\"requestVideo()\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push("Request Video");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<input id=\"input\"/>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<button onclick=\"playVideo()\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("Play Video");
jade_debug.shift();
jade_debug.shift();
buf.push("</button>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<video id=\"video\" controls=\"controls\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</video>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<div id=\"container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<script src=\"bower_components/jquery/dist/jquery.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<script src=\"bower_components/socket.io-client/socket.io.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<script src=\"bower_components/mediaelement/build/mediaelement-and-player.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "/Users/jess/labs/2014/home/iot/spot/test_client/index.jade" });
buf.push("<script src=\"script.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();}.call(this,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "link(rel=\"stylesheet\" src=\"bower_components/mediaelement/build/mediaelementplayer.css\")\nh1 Spot test\n\nbutton(onclick=\"requestVideo()\") Request Video\ninput#input\nbutton(onclick=\"playVideo()\") Play Video\n\nvideo#video(controls)\n//- object#object(data=\"movie.mp4\")\n#container\n//- embed#embed(type=\"application/x-shockwave-flash\")\n\nscript(src=\"bower_components/jquery/dist/jquery.js\")\nscript(src=\"bower_components/socket.io-client/socket.io.js\")\nscript(src=\"bower_components/mediaelement/build/mediaelement-and-player.js\")\nscript(src=\"script.js\")\n");
}
}